"""
Tracking state and output data models for Phase 2.
"""

from enum import Enum
from dataclasses import dataclass, asdict
from typing import Tuple, Optional, Dict, Any
from .detection import DetectionResult


class TrackingState(str, Enum):
    """
    Finite State Machine operational states for coarse alignment target tracking.
    """
    SEARCHING = "SEARCHING"       # Searching for beacon; no lock established
    ACQUIRED = "ACQUIRED"         # Beacon detected initially (< N frames); confirming lock
    TRACKING = "TRACKING"         # Stable temporal tracking lock confirmed
    LOST = "LOST"                 # Target lost for > N frames
    REACQUIRED = "REACQUIRED"     # Target re-detected after being lost; confirming re-lock


@dataclass(frozen=True)
class TrackerOutput:
    """
    Complete state packet generated by the vision tracking pipeline per frame.
    Decoupled from ground truth.
    """
    state: TrackingState                       # Current FSM tracking state
    is_tracking: bool                          # True if state is ACQUIRED, TRACKING, or REACQUIRED
    raw_detection: DetectionResult             # Raw frame detector result
    filtered_centroid: Optional[Tuple[float, float]] = None # Kalman-filtered position (u, v)
    filtered_velocity: Optional[Tuple[float, float]] = None # Kalman-filtered velocity (u_dot, v_dot) in px/s
    is_predicted: bool = False                 # True if Kalman state was coasted without fresh detection
    consecutive_detections: int = 0            # Number of consecutive frames with successful detections
    consecutive_losses: int = 0                # Number of consecutive frames without detections
    timestamp: float = 0.0                     # Timestamp of frame in seconds
    frame_index: int = 0                       # Sequence index
    total_processing_time_ms: float = 0.0      # Total pipeline latency in milliseconds

    def to_dict(self) -> Dict[str, Any]:
        return {
            "state": self.state.value,
            "is_tracking": self.is_tracking,
            "raw_centroid": self.raw_detection.centroid,
            "filtered_centroid": self.filtered_centroid,
            "filtered_velocity": self.filtered_velocity,
            "is_predicted": self.is_predicted,
            "consecutive_detections": self.consecutive_detections,
            "consecutive_losses": self.consecutive_losses,
            "timestamp": self.timestamp,
            "frame_index": self.frame_index,
            "total_processing_time_ms": self.total_processing_time_ms,
        }
